FROM registry.access.redhat.com/ubi9/nodejs-22 AS front-builder

USER root

WORKDIR /opt/openaev-build/openaev-front
COPY openaev-front ./
RUN set -eux; \
    npm install -g corepack; \
    yarn install; \
    yarn build;


FROM registry.access.redhat.com/ubi9/openjdk-21 AS api-builder

USER root

RUN set -eux; \
    microdnf install -y maven; \
    microdnf clean all; \
    mvn --version;

WORKDIR /opt/openaev-build/openaev
COPY openaev-model ./openaev-model
COPY openaev-framework ./openaev-framework
COPY openaev-api ./openaev-api
COPY pom.xml ./pom.xml
COPY --from=front-builder /opt/openaev-build/openaev-front/builder/prod/build ./openaev-front/builder/prod/build
RUN mvn install -DskipTests -Pdev


FROM registry.access.redhat.com/ubi9/openjdk-21-runtime AS app

USER root

RUN set -eux; \
    curl -L -o /usr/bin/tini https://github.com/krallin/tini/releases/download/v0.19.0/tini; \
    echo "93dcc18adc78c65a028a84799ecf8ad40c936fdfc5f2a57b1acda5a8117fa82c /usr/bin/tini" | sha256sum -c -; \
    chmod +x /usr/bin/tini;

WORKDIR /opt/openaev
COPY --from=api-builder /opt/openaev-build/openaev/openaev-api/target/openaev-api.jar ./

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["java", "-jar", "openaev-api.jar"]
