export const USERS_CAPABILITIES_PATH = 'users-capabilities';

export const PLATFORM_ROUTE = '/admin/platform';
export const PLATFORM_USERS_CAPABILITIES_ROUTE = `${PLATFORM_ROUTE}/${USERS_CAPABILITIES_PATH}`;

export const PLATFORM_ROLES_PATH = 'roles';
export const PLATFORM_ROLES_ROUTE = `${PLATFORM_USERS_CAPABILITIES_ROUTE}/${PLATFORM_ROLES_PATH}`;

export const PLATFORM_GROUPS_PATH = 'groups';
export const PLATFORM_GROUPS_ROUTE = `${PLATFORM_USERS_CAPABILITIES_ROUTE}/${PLATFORM_GROUPS_PATH}`;

export const PLATFORM_USERS_PATH = 'users';
export const PLATFORM_USERS_ROUTE = `${PLATFORM_USERS_CAPABILITIES_ROUTE}/${PLATFORM_USERS_PATH}`;
